### ISSUE TITLE
Spectrum Library in Android

### ISSUE THREAD

**Issue by JeyanthInba** [rororor/astetho#1]
I am doing frequency spectrum analysis for FM in android,Could you please suggest a library for frequency spectrum plot.

**Comment by rororor** [comment]
I have tried MPAndroidChart and HelloCharts - too slow for fast real-time plotting, too complex API, many features are unnecessary.
Much quicker to draw directly on View's Canvas

**Comment by JeyanthInba** [comment]
can you give me a small example on how the frequency is plotted by using MPandroid chart library...I am a beginner and I tried with data,it is plotting .But for frequency spectrum,i dont have an idea.Need Support.

**Comment by JeyanthInba** [comment]
Thank you !

**Comment by JeyanthInba** [comment]
In your astetho code,Could you please tell me what you have used for the frequency spectrum.

**Comment by rororor** [comment]
FFT transform code - in Fft.java, FftRec class captures audio from microphone, calculates RMS and spectrum, and displays it on FftView widget
